#!/usr/bin/env python3
"""Make volcano plots from computed metrics.

Inputs:
  Derived metrics (e.g., CSV generated by 01_disproportionality.py)
Outputs:
  figures/fig4_volcano.png
"""
from pathlib import Path
import matplotlib.pyplot as plt

def main():
    root = Path(__file__).resolve().parents[1]
    out_dir = root / "figures"
    out_dir.mkdir(parents=True, exist_ok=True)

    plt.figure()
    plt.title("Placeholder: Volcano plot")
    plt.xlabel("lnROR")
    plt.ylabel("-log10(p-value)")
    plt.savefig(out_dir / "fig_placeholder_volcano.png", dpi=300)
    print("Saved figure:", out_dir / "fig_placeholder_volcano.png")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
